### ISSUE TITLE
Goal Issue

### ISSUE THREAD

**Issue by picnpost** [Studio164a/appthemer-crowdfunding#10]
Hi,

I´m working on a wordpress crowdfunding theme that includes Easy Digital Downloads and Appthemer-Crowfunding. Since my last update of Easy Digital Downloads plugin, I´ve noticed a problem with Appthemer Crowfunding.
The issue is that the system does not allow me to put the price in projects. Every time I put the goal-price in the backend and save the project, the price marked disappears, and it´s reset to 0,00$ again.

Hope you can help me.

**Comment by ericnicolaas** [comment]
Hi @picnpost, 

Try updating to the latest version here: https://github.com/Studio164a/appthemer-crowdfunding/releases/tag/v1.9.6

Also, just so you know, we're not actively developing or supporting this plugin anymore, so there is no guarantee this will continue working in the future. Our focus is on wpcharitable.com now :) 

If you're developing a theme with some crowdfunding/fundraising aspect, Charitable would be a better choice since it is supported and actively developed. 

Cheers, 
Eric
